=== MoatLab/FEMU/roms/edk2/MdePkg/Library/MipiSysTLib/mipisyst/collateral/sys-t_1-0.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
 Copyright(c) 2018, MIPI Alliance, Inc.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
 are met:

 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in
   the documentation and/or other materials provided with the
   distribution.

 * Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived
   from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.mipi.org/1.0/sys-t"
    xmlns="http://www.mipi.org/1.0/sys-t"
    xmlns:syst="http://www.mipi.org/1.0/sys-t"
    elementFormDefault="qualified">

  <xs:element name="Collateral">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element name ="Client">
          <xs:complexType>
            <xs:sequence>
              <xs:element name ="Guids">
                <xs:complexType>
                  <xs:sequence minOccurs="1" maxOccurs="unbounded">
                    <xs:element name ="Guid" type="typeGuid"/>
                  </xs:sequence>
                </xs:complexType>
                <xs:unique name="uniqueGuidIds">
                  <xs:selector xpath="syst:Guid" />
                  <xs:field xpath="@ID" />
                </xs:unique>
              </xs:element>
              <xs:element name ="Builds" minOccurs="0" maxOccurs="1" >
                <xs:complexType>
                  <xs:sequence minOccurs="1" maxOccurs="unbounded">
                    <xs:element name ="Build" type="typeBuild"/>
                  </xs:sequence>
                </xs:complexType>
                <xs:unique name="uniqueBuildIds">
                  <xs:selector xpath="syst:Build" />
                  <xs:field xpath="@ID" />
                </xs:unique>
              </xs:element>
              <xs:element name ="Options" minOccurs="0" maxOccurs="1" >
                <xs:complexType>
                  <xs:sequence minOccurs="1" maxOccurs="unbounded">
                    <xs:element name ="Option" type="typeOption"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name ="Modules" minOccurs="0" maxOccurs="1" >
                <xs:complexType>
                  <xs:sequence minOccurs="1" maxOccurs="unbounded">
                    <xs:element name ="Module" type="typeModule"/>
                  </xs:sequence>
                </xs:complexType>
                <xs:unique name="uniqueModuleIds">
                  <xs:selector xpath="syst:Module" />
                  <xs:field xpath="@ID" />
                </xs:unique>
              </xs:element>
              <xs:element name="SourceFiles"  minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence minOccurs="1" maxOccurs="unbounded">
                    <xs:element name ="File" type="typeFile"/>
                  </xs:sequence>
                </xs:complexType>
                <xs:unique name="uniqueSourceIds">
                  <xs:selector xpath="syst:File" />
                  <xs:field xpath="@ID" />
                </xs:unique>
              </xs:element>
              <xs:element name="Catalog32" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence minOccurs="1" maxOccurs="unbounded">
                    <xs:element name ="Format" type="typeCatalog32"/>
                  </xs:sequence>
                </xs:complexType>
                <xs:unique name="uniqueCatalog32Ids">
                  <xs:selector xpath="syst:Format" />
                  <xs:field xpath="@ID" />
                </xs:unique>
              </xs:element>
              <xs:element name="Catalog64" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence minOccurs="1" maxOccurs="unbounded">
                    <xs:element name ="Format" type="typeCatalog64"/>
                  </xs:sequence>
                </xs:complexType>
                <xs:unique name="uniqueCatalog64Ids">
                  <xs:selector xpath="syst:Format" />
                  <xs:field xpath="@ID" />
                </xs:unique>
              </xs:element>
              <xs:element name="Short32" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence minOccurs="1" maxOccurs="unbounded">
                    <xs:element name ="Format" type="typeShort32"/>
                  </xs:sequence>
                </xs:complexType>
                <xs:unique name="uniqueShort32Ids">
                  <xs:selector xpath="syst:Format" />
                  <xs:field xpath="@ID" />
                </xs:unique>
            </xs:element>
              <xs:element name="Short64" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence minOccurs="1" maxOccurs="unbounded">
                    <xs:element name ="Format" type="typeShort64"/>
                  </xs:sequence>
                </xs:complexType>
                <xs:unique name="uniqueShort64Ids">
                  <xs:selector xpath="syst:Format" />
                  <xs:field xpath="@ID" />
                </xs:unique>
              </xs:element>
              <xs:element name="Write" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence minOccurs="1" maxOccurs="unbounded">
                    <xs:element name ="Protocol" type="Write"/>
                  </xs:sequence>
                </xs:complexType>
                <xs:unique name="uniqueWriteIds">
                  <xs:selector xpath="syst:Protocol" />
                  <xs:field xpath="@ID" />
                </xs:unique>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Name"  type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="typeGuid">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="ID"  type="guidString" use="required" />
        <xs:attribute name="Mask" type="guidString" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="typeBuild">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="ID" type="unsigned64" use="required" />
        <xs:attribute name="Mask" type="unsigned64" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- Complex SyS-T XML type definitions -->

  <xs:complexType name="typeModule">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="ID" type="unsigned64" use="required" />
        <xs:attribute name="Mask" type="unsigned64" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="typeOption">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="Name" type="xs:string" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="typeFile">
    <xs:simpleContent>
      <xs:extension base="nonEmptyString">
        <xs:attribute name="ID" type="unsigned32" use="required" />
        <xs:attribute name="Mask" type="unsigned32" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="typeCatalog32">
    <xs:simpleContent>
      <xs:extension base="nonEmptyString">
        <xs:attribute name="ID" type="unsigned32" use="required" />
        <xs:attribute name="Mask" type="unsigned32" use="optional" />
        <xs:attribute name="File" type="unsigned32" use="optional"/>
        <xs:attribute name="Line" type="unsigned32" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="typeCatalog64">
    <xs:simpleContent>
      <xs:extension base="nonEmptyString">
        <xs:attribute name="ID" type="unsigned64" use="required" />
        <xs:attribute name="Mask" type="unsigned64" use="optional" />
        <xs:attribute name="File" type="unsigned32" use="optional"/>
        <xs:attribute name="Line" type="unsigned32" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="typeShort32">
    <xs:simpleContent>
      <xs:extension base="nonEmptyString">
        <xs:attribute name="ID" type="unsigned32" use="required" />
        <xs:attribute name="Mask" type="unsigned32" use="optional" />
        <xs:attribute name="File" type="unsigned32" use="optional"/>
        <xs:attribute name="Line" type="unsigned32" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="typeShort64">
    <xs:simpleContent>
      <xs:extension base="nonEmptyString">
        <xs:attribute name="ID" type="unsigned64" use="required" />
        <xs:attribute name="Mask" type="unsigned64" use="optional" />
        <xs:attribute name="File" type="unsigned32" use="optional"/>
        <xs:attribute name="Line" type="unsigned32" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="Write">
    <xs:simpleContent>
      <xs:extension base="nonEmptyString">
        <xs:attribute name="ID" type="unsigned6" use="required" />
        <xs:attribute name="Mask" type="unsigned6" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- Simple type definitions -->

  <xs:simpleType name="nonEmptyString">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="unsigned32">
    <xs:restriction base="xs:string">
      <xs:pattern value="0x[0-9a-fA-F]{1,8}|0|[1-9][0-9]{1,9}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="unsigned64">
    <xs:restriction base="xs:string">
      <xs:pattern value="0x[0-9a-fA-F]{1,16}|0|[1-9][0-9]{1,20}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="unsigned6">
    <xs:restriction base="xs:string">
      <xs:pattern value="0x[0-9a-fA-F]{0,2}|0|[1-9][0-9]{1,2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="guidString">
    <xs:restriction base="xs:string">
      <xs:pattern value="\{[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\}"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== MoatLab/FEMU/roms/edk2/MdePkg/Library/MipiSysTLib/mipisyst/collateral/example_collateral.xml
<?xml version="1.0" encoding="utf-8"?>
<syst:Collateral xmlns:syst="http://www.mipi.org/1.0/sys-t"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.mipi.org/1.0/sys-t
                        https://www.mipi.org/schema/sys-t/sys-t_1-0.xsd">

  <!--
  A SyS-T collateral file starts with one syst:Collateral element
  and contains at least one syst:Client child node.
 -->
  <syst:Client Name="example">

    <!--
    List of message GUIDs for this client:
    A GUID is a 128bit numeric UUID following RFC 4122.
    Clients that are identified by transport layer properties
    can use pseudo GUID values to identify their messages. A
    pseudo GUID is defined as a GUID with bit 71 set to zero.
    The following encoding might be used for clients identified
    by MIPI System Trace Protocol (STP) master/channel pairs:

     {00000000-<MasterID>-<ChannelID>-<Origin>00-000000000000}

    A Mask attribute can be added to define which bits of the GUID are
    used for comparison. Without a mask, all bits need to match.
    The example below makes the catalog valid for all channels from the
    STP master value 0x644, or messages with the "494E..." GUID in their
    payload.
    -->
    <syst:Guids>
      <syst:Guid ID=  "{00000000-0644-0000-0000-000000000000}"
                 Mask="{00000000-FFFF-0000-8000-000000000000}"><![CDATA[kernel]]></syst:Guid>
      <syst:Guid ID="{494E5443-6F64-43D1-93F0-F3D49D92670C}"><![CDATA[user]]></syst:Guid>
    </syst:Guids>

    <!--
    Define for which client build versions this collateral is valid.
    Builds are expressed as values up to 64 bits in size, and can include a
    mask that defines which bits need to match with a client build version
    message.
    -->
    <syst:Builds>
      <syst:Build ID="0x00010000" Mask="0xFFFF0000" ><![CDATA[SW Build 1.x]]></syst:Build>
      <syst:Build ID="0x00020000" Mask="0xFFFF0000" ><![CDATA[SW Build 2.x]]></syst:Build>
    </syst:Builds>

     <!--
     Settings to guide decoding tools what to do in cases
     where several options are possible. The example below tells
     a decoder to interprete SyS-T message timstamps only as an
     informal field, but not the message creation time.
     -->
    <syst:Options>
      <syst:Option Name="syst:timestamp">displayAsField</syst:Option>
    </syst:Options>

    <!--
    Provide ID to name mapping for Origin header field values.
    -->
    <syst:Modules>
      <syst:Module ID="0x1"><![CDATA[kernel]]></syst:Module>
      <syst:Module ID="0x2"><![CDATA[user]]></syst:Module>
  </syst:Modules>

    <!--
    Define the mapping of the numeric File-ID to source files.
    This table is optional and only needed if source references are used
    by the Catalog32 or Catalog64 elements.
    -->
    <syst:SourceFiles>
      <syst:File ID="0x00000001"><![CDATA[example/src/main.c]]></syst:File>
      <syst:File ID="0x00000002"><![CDATA[example/h/example.h]]></syst:File>
    </syst:SourceFiles>

    <!--
    Define the mapping of catalog message ID to human-readable strings.
    This table is optional and only needed if catalog messages are used.
    A message can have optional "File" and "Line" attributes to specify the
    source position of the instrumentation call. A decoder uses the
    information from these attributes if the message payload doesn't provide
    explicit location information.
    -->
    <syst:Catalog32>
      <syst:Format ID="0x00000001" File="0x00000001" Line="23"><![CDATA[This is example %d.%d]]></syst:Format>
      <syst:Format ID="0x00000002" File="0x00000002" Line="72"><![CDATA[task switch %x->%x]]></syst:Format>
    </syst:Catalog32>

    <syst:Catalog64>
      <syst:Format ID="0x0000000000000001"><![CDATA[error %d]]></syst:Format>
    </syst:Catalog64>

    <!--
    Define short message mapping from 28-Bit ID to user visible string.
    -->
    <syst:Short32>
      <syst:Format ID="0x0000000" Mask="0xFFFFFF0"><![CDATA[Fatal Error code]]></syst:Format>
      <syst:Format ID="0x0000013"><![CDATA[state ready]]></syst:Format>
      <syst:Format ID="0x000001A"><![CDATA[state halt]]></syst:Format>
    </syst:Short32>

    <!--
    Define short message mapping from 60-Bit ID to user visible string.
    -->
    <syst:Short64>
      <syst:Format ID="0x123456700000000" Mask="0xFFFFFFF00000000"><![CDATA[warning state]]></syst:Format>

    </syst:Short64>

    <!--
    Specify raw message protocol id assignment
    -->
    <syst:Write>
      <syst:Protocol ID="0x01"><![CDATA[console]]></syst:Protocol>
      <syst:Protocol ID="0x02"><![CDATA[console]]></syst:Protocol>
      <syst:Protocol ID="0x03"><![CDATA[ftrace]]></syst:Protocol>
      <syst:Protocol ID="0x20" Mask="0x30"><![CDATA[reserved]]></syst:Protocol>
    </syst:Write>

</syst:Client>

</syst:Collateral>
